import {Injectable} from '@angular/core';

import {Food} from './food';

export const FOODS:Food[] = [
  {name: 'Abricot au sirop', calories: 108, proteins: 1, carbohydrates: 28, fats: 0, ig: 0},
  {name: 'Abricot en boîte de conserve', calories: 88, proteins: 1, carbohydrates: 21, fats: 0, ig: 0},
  {name: 'Abricot frais', calories: 50, proteins: 1, carbohydrates: 11, fats: 0, ig: 0},
  {name: 'Abricot sec', calories: 200, proteins: 4, carbohydrates: 39, fats: 1, ig: 0},
  {name: 'Acras de morue', calories: 193, proteins: 20, carbohydrates: 11, fats: 8, ig: 0},
  {name: 'After Eight', calories: 414, proteins: 3, carbohydrates: 72, fats: 13, ig: 0},
  {name: 'Agneau sauté', calories: 238, proteins: 21, carbohydrates: 1, fats: 17, ig: 0},
  {name: 'Ail', calories: 149, proteins: 6.4, carbohydrates: 33, fats: 0.5, ig: 0},
  {name: 'Ail en poudre', calories: 332.3, proteins: 16.8, carbohydrates: 72.7, fats: 0.8, ig: 0},
  {name: 'Ail frais', calories: 133, proteins: 7, carbohydrates: 25, fats: 1, ig: 0},
  {name: 'Ailloli', calories: 704, proteins: 3, carbohydrates: 3, fats: 76, ig: 0},
  {name: 'Airelle en boîte de conserve', calories: 126, proteins: 0, carbohydrates: 30, fats: 0, ig: 0},
  {name: 'Airelle fraîche', calories: 25, proteins: 0, carbohydrates: 1, fats: 0, ig: 0},
  {name: 'Algue marine', calories: 239, proteins: 12, carbohydrates: 42, fats: 3, ig: 0},
  {name: 'Alose crue', calories: 197, proteins: 17, carbohydrates: 0, fats: 14, ig: 0},
  {name: 'Alose grillée au four', calories: 252, proteins: 22, carbohydrates: 0, fats: 18, ig: 0},
  {name: 'Aloyau de boeuf', calories: 266, proteins: 17, carbohydrates: 0, fats: 22, ig: 0},
  {name: 'Aloyau de veau', calories: 175, proteins: 19, carbohydrates: 0, fats: 11, ig: 0},
  {name: 'Amandes', calories: 575, proteins: 20, carbohydrates: 4, fats: 54, ig: 0},
  {name: 'Amandes blanchies séchées', calories: 586, proteins: 20.4, carbohydrates: 18.5, fats: 52.5, ig: 0},
  {name: 'Amandes séchées', calories: 589, proteins: 20, carbohydrates: 20.4, fats: 52, ig: 0},
  {name: 'Amandine (en boulangerie)', calories: 411, proteins: 8, carbohydrates: 41, fats: 24, ig: 0},
  {name: 'Amuse gueule à base de maïs', calories: 507, proteins: 8, carbohydrates: 56, fats: 27, ig: 0},
  {name: 'Ananas au sirop', calories: 65, proteins: 0, carbohydrates: 16, fats: 0, ig: 0},
  {name: 'Ananas frais', calories: 48, proteins: 1, carbohydrates: 11, fats: 0, ig: 0},
  {name: 'Anchois à l\'huile', calories: 160, proteins: 22, carbohydrates: 0, fats: 8, ig: 0},
  {name: 'Anchois en boîte de conserve', calories: 160, proteins: 22, carbohydrates: 0, fats: 13, ig: 0},
  {name: 'Anchois frais', calories: 129, proteins: 20, carbohydrates: 0, fats: 14, ig: 0},
  {name: 'Andouillette', calories: 235, proteins: 18, carbohydrates: 1, fats: 18, ig: 0},
  {name: 'Aneth fraîche', calories: 43, proteins: 3.5, carbohydrates: 7, fats: 1, ig: 0},
  {name: 'Aneth séchée', calories: 253, proteins: 20, carbohydrates: 55.8, fats: 4.4, ig: 0},
  {name: 'Anguille cuite au four', calories: 230, proteins: 24, carbohydrates: 0, fats: 15, ig: 0},
  {name: 'Anguille fumée', calories: 328, proteins: 19, carbohydrates: 0, fats: 28, ig: 0},
  {name: 'Apericubes', calories: 160, proteins: 10, carbohydrates: 1, fats: 12, ig: 0},
  {name: 'Araignée de boeuf', calories: 200, proteins: 22, carbohydrates: 0, fats: 15, ig: 0},
  {name: 'Araignée de mer', calories: 95, proteins: 16, carbohydrates: 1, fats: 3, ig: 0},
  {name: 'Arôme de vanille', calories: 56, proteins: 0, carbohydrates: 14.4, fats: 0, ig: 0},
  {name: 'Arôme de vanille (alcoolisé)', calories: 237, proteins: 0, carbohydrates: 2.4, fats: 0, ig: 0},
  {name: 'Artichaut cuit', calories: 18, proteins: 3, carbohydrates: 2, fats: 0, ig: 0},
  {name: 'Asperge cuite', calories: 19, proteins: 3, carbohydrates: 2, fats: 0, ig: 0},
  {name: 'Asperge en boîte de conserve', calories: 24, proteins: 2, carbohydrates: 3, fats: 0, ig: 0},
  {name: 'Asperges', calories: 28, proteins: 2.4, carbohydrates: 4, fats: 0.3, ig: 0},
  {name: 'Aubergine crue', calories: 18, proteins: 1, carbohydrates: 3, fats: 0, ig: 0},
  {name: 'Aubergine cuite', calories: 18, proteins: 1, carbohydrates: 3, fats: 0, ig: 0},
  {name: 'Autruche en steak', calories: 106, proteins: 22, carbohydrates: 0, fats: 2, ig: 0},
  {name: 'Avocat', calories: 208, proteins: 1.8, carbohydrates: 7.5, fats: 19, ig: 0},
  {name: 'Avocat aux crevettes', calories: 97, proteins: 5, carbohydrates: 1, fats: 8, ig: 0},
  {name: 'Avocat nature', calories: 138, proteins: 2, carbohydrates: 1, fats: 15, ig: 0},
  {name: 'Baba au rhum Chantilly', calories: 183, proteins: 2, carbohydrates: 34, fats: 3, ig: 0},
  {name: 'Babybel', calories: 353, proteins: 29, carbohydrates: 3, fats: 25, ig: 0},
  {name: 'Bacon', calories: 270, proteins: 17, carbohydrates: 0, fats: 22, ig: 0},
  {name: 'Bacon (tranche)', calories: 54, proteins: 3.4, carbohydrates: 0.04, fats: 4.4, ig: 0},
  {name: 'Bacon fumé cuit', calories: 132, proteins: 23, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Baguette de pain', calories: 271, proteins: 8, carbohydrates: 56, fats: 1, ig: 0},
  {name: 'Baguette viennoise', calories: 207, proteins: 7, carbohydrates: 42, fats: 2, ig: 0},
  {name: 'Banana split', calories: 206, proteins: 4, carbohydrates: 27, fats: 9, ig: 0},
  {name: 'Banane', calories: 100, proteins: 1.3, carbohydrates: 22.7, fats: 0.5, ig: 0},
  {name: 'Banane fraîche', calories: 89, proteins: 1, carbohydrates: 20, fats: 1, ig: 0},
  {name: 'Banane séchée', calories: 292, proteins: 4, carbohydrates: 66, fats: 1, ig: 0},
  {name: 'Bar (poisson)', calories: 91, proteins: 20, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Bar loup', calories: 98, proteins: 20, carbohydrates: 0, fats: 2, ig: 0},
  {name: 'Barbue (poisson)', calories: 118, proteins: 18, carbohydrates: 0, fats: 5, ig: 0},
  {name: 'Barre chocolatée en biscuit', calories: 498, proteins: 7, carbohydrates: 63, fats: 25, ig: 0},
  {name: 'Barre chocolatée enrobée', calories: 456, proteins: 5, carbohydrates: 66, fats: 19, ig: 0},
  {name: 'Barre minceur diététique', calories: 357, proteins: 27, carbohydrates: 46, fats: 7, ig: 0},
  {name: 'Bas carré de veau', calories: 173, proteins: 28, carbohydrates: 0, fats: 7, ig: 0},
  {name: 'Basilic', calories: 27, proteins: 3, carbohydrates: 4, fats: 1, ig: 0},
  {name: 'Basilic (fines herbes)', calories: 251, proteins: 14.4, carbohydrates: 61, fats: 4, ig: 0},
  {name: 'Basilic frais', calories: 27, proteins: 2.5, carbohydrates: 4.3, fats: 0.6, ig: 0},
  {name: 'Batavia assaisonnée', calories: 116, proteins: 2, carbohydrates: 4, fats: 11, ig: 0},
  {name: 'Batavia nature', calories: 25, proteins: 2, carbohydrates: 4, fats: 0, ig: 0},
  {name: 'Baudroie (ou lotte) cuit vapeur', calories: 79, proteins: 18, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Bavette de boeuf', calories: 200, proteins: 19, carbohydrates: 0, fats: 10, ig: 0},
  {name: 'Beaufort', calories: 401, proteins: 27, carbohydrates: 0, fats: 33, ig: 0},
  {name: 'Beignet à la confiture', calories: 335, proteins: 7, carbohydrates: 47, fats: 14, ig: 0},
  {name: 'Betterave rouge crue', calories: 41, proteins: 2, carbohydrates: 8, fats: 0, ig: 0},
  {name: 'Betterave rouge cuite', calories: 42, proteins: 2, carbohydrates: 9, fats: 0, ig: 0},
  {name: 'Bettes', calories: 21, proteins: 2, carbohydrates: 2, fats: 1, ig: 0},
  {name: 'Beurre', calories: 741, proteins: 0.8, carbohydrates: 0, fats: 82, ig: 0},
  {name: 'Beurre allégé', calories: 401, proteins: 7, carbohydrates: 1, fats: 41, ig: 0},
  {name: 'Beurre demi sel', calories: 740, proteins: 1, carbohydrates: 1, fats: 82, ig: 0},
  {name: 'Biche', calories: 116, proteins: 33, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Bière blonde (33 cl)', calories: 146, proteins: 1.07, carbohydrates: 13, fats: 0, ig: 0},
  {name: 'Bière ordinaire', calories: 33, proteins: 0.4, carbohydrates: 3.5, fats: 0, ig: 0},
  {name: 'Bière ordinaire (100 ml)', calories: 38, proteins: 0, carbohydrates: 3, fats: 0, ig: 0},
  {name: 'Bière pression (100 ml)', calories: 57, proteins: 0, carbohydrates: 11, fats: 0, ig: 0},
  {name: 'Bière sans alcool (100 ml)', calories: 42, proteins: 0, carbohydrates: 6, fats: 0, ig: 0},
  {name: 'Bifteck boeuf', calories: 174, proteins: 25, carbohydrates: 0.5, fats: 8, ig: 0},
  {name: 'Bifteck cheval', calories: 123, proteins: 23, carbohydrates: 1, fats: 3, ig: 0},
  {name: 'Bifteck grillé', calories: 148, proteins: 28, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Big Mac', calories: 493, proteins: 26, carbohydrates: 39, fats: 24, ig: 0},
  {name: 'Bigorneau', calories: 135, proteins: 26, carbohydrates: 1, fats: 5, ig: 0},
  {name: 'Biscotte', calories: 392, proteins: 10, carbohydrates: 79, fats: 4, ig: 0},
  {name: 'Biscuit au chocolat', calories: 493, proteins: 7, carbohydrates: 60, fats: 24, ig: 0},
  {name: 'Biscuit sablé', calories: 457, proteins: 5.5, carbohydrates: 75, fats: 15, ig: 0},
  {name: 'Biscuit sec', calories: 429, proteins: 9, carbohydrates: 70, fats: 12, ig: 0},
  {name: 'Bison', calories: 110, proteins: 35, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Bisque de homard (100 ml)', calories: 27, proteins: 3, carbohydrates: 2, fats: 1, ig: 0},
  {name: 'Blanc de poulet avec peau', calories: 216, proteins: 17, carbohydrates: 0, fats: 16, ig: 0},
  {name: 'Blanc de poulet sans peau', calories: 115, proteins: 22, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Blanc d\'oeuf frais, cru', calories: 50, proteins: 10.5, carbohydrates: 1, fats: 0, ig: 0},
  {name: 'Blanc d\'oeuf normal', calories: 46, proteins: 10, carbohydrates: 1, fats: 0, ig: 0},
  {name: 'Blanquette de veau', calories: 160, proteins: 16, carbohydrates: 3, fats: 10, ig: 0},
  {name: 'Blettes', calories: 21, proteins: 2, carbohydrates: 2, fats: 1, ig: 0},
  {name: 'Bleu d\'Auvergne', calories: 398, proteins: 22, carbohydrates: 1, fats: 34, ig: 0},
  {name: 'Blinis', calories: 323, proteins: 7, carbohydrates: 35, fats: 17, ig: 0},
  {name: 'Boeuf Bourguignon', calories: 114, proteins: 12, carbohydrates: 2, fats: 5, ig: 0},
  {name: 'Boeuf braisé', calories: 232, proteins: 31, carbohydrates: 0, fats: 12, ig: 0},
  {name: 'Boisson au chocolat (100 ml)', calories: 388, proteins: 6, carbohydrates: 80, fats: 3, ig: 0},
  {name: 'Bonbon', calories: 396, proteins: 1, carbohydrates: 99, fats: 0, ig: 0},
  {name: 'Boudin blanc', calories: 291, proteins: 11, carbohydrates: 1, fats: 27, ig: 0},
  {name: 'Boudin noir', calories: 344, proteins: 11, carbohydrates: 2, fats: 33, ig: 0},
  {name: 'Bouillabaisse', calories: 99, proteins: 13, carbohydrates: 2, fats: 4, ig: 0},
  {name: 'Bouillon de cube', calories: 180, proteins: 20, carbohydrates: 8, fats: 8, ig: 0},
  {name: 'Bouillon de légumes (100 ml)', calories: 215, proteins: 0, carbohydrates: 54, fats: 0, ig: 0},
  {name: 'Bouillon de volaille', calories: 307, proteins: 9.6, carbohydrates: 65.6, fats: 7.5, ig: 0},
  {name: 'Bounty noix de coco', calories: 470, proteins: 4, carbohydrates: 57, fats: 26, ig: 0},
  {name: 'Boursault', calories: 355, proteins: 31, carbohydrates: 8, fats: 22, ig: 0},
  {name: 'Boursin ail et fines herbes', calories: 414, proteins: 7, carbohydrates: 2, fats: 42, ig: 0},
  {name: 'Boursin allégé', calories: 186, proteins: 12, carbohydrates: 6, fats: 12, ig: 0},
  {name: 'Brandade de morue', calories: 299, proteins: 5, carbohydrates: 31, fats: 16, ig: 0},
  {name: 'Bretzel', calories: 361, proteins: 9, carbohydrates: 74, fats: 3, ig: 0},
  {name: 'Brochet', calories: 93, proteins: 21, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Cabillaud', calories: 74, proteins: 16, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Cacahuètes', calories: 576, proteins: 23, carbohydrates: 22, fats: 44, ig: 0},
  {name: 'Café filtre (1 tasse)', calories: 4.3, proteins: 0, carbohydrates: 0.74, fats: 0.01, ig: 0},
  {name: 'Café nescafe (1 tasse)', calories: 4, proteins: 0, carbohydrates: 0.8, fats: 0, ig: 0},
  {name: 'Caille', calories: 115, proteins: 24, carbohydrates: 0.5, fats: 1.5, ig: 0},
  {name: 'Cake', calories: 413, proteins: 6.4, carbohydrates: 54.8, fats: 18.7, ig: 0},
  {name: 'Calmar frit', calories: 167, proteins: 15, carbohydrates: 6.62, fats: 8.36, ig: 0},
  {name: 'Calmar nature', calories: 92, proteins: 16.5, carbohydrates: 2.6, fats: 1.7, ig: 0},
  {name: 'Camembert ( portion 50 g)', calories: 149.5, proteins: 8.75, carbohydrates: 0.9, fats: 12.35, ig: 0},
  {name: 'Camenbert', calories: 299, proteins: 17.5, carbohydrates: 1.8, fats: 24.7, ig: 0},
  {name: 'Canard rôti', calories: 196, proteins: 23.5, carbohydrates: 0, fats: 11, ig: 0},
  {name: 'Cannelle', calories: 261.3, proteins: 3.9, carbohydrates: 79.8, fats: 3, ig: 0},
  {name: 'Câpres en boîte', calories: 23, proteins: 2.4, carbohydrates: 4.9, fats: 0.9, ig: 0},
  {name: 'Cardamome', calories: 311.3, proteins: 10.8, carbohydrates: 68.5, fats: 6.7, ig: 0},
  {name: 'Carotte', calories: 40, proteins: 1, carbohydrates: 8.5, fats: 0, ig: 0},
  {name: 'Carpe', calories: 110, proteins: 18.5, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Carrelet (poisson)', calories: 65, proteins: 15, carbohydrates: 0.5, fats: 0.6, ig: 0},
  {name: 'Cassis', calories: 54, proteins: 1, carbohydrates: 12, fats: 0, ig: 0},
  {name: 'Caviar', calories: 330, proteins: 30, carbohydrates: 7.5, fats: 20, ig: 0},
  {name: 'Celeri feuille', calories: 21, proteins: 1.3, carbohydrates: 3.5, fats: 0, ig: 0},
  {name: 'Celeri racine', calories: 44, proteins: 2, carbohydrates: 8.5, fats: 0, ig: 0},
  {name: 'Cereales nature', calories: 489, proteins: 12, carbohydrates: 65, fats: 22, ig: 0},
  {name: 'Cerfeuil', calories: 236.6, proteins: 23, carbohydrates: 49, fats: 3.9, ig: 0},
  {name: 'Cerises', calories: 68, proteins: 1, carbohydrates: 15, fats: 0.4, ig: 0},
  {name: 'Cervelle d\'agneau poelée', calories: 228, proteins: 14.4, carbohydrates: 0, fats: 18.9, ig: 0},
  {name: 'Chair à saucisse', calories: 421, proteins: 15, carbohydrates: 1, fats: 38, ig: 0},
  {name: 'Champagne', calories: 60, proteins: 0, carbohydrates: 8.6, fats: 0, ig: 0},
  {name: 'Champignons', calories: 28, proteins: 2, carbohydrates: 4.5, fats: 0.3, ig: 0},
  {name: 'Charlotte (gâteau)', calories: 306, proteins: 5.7, carbohydrates: 34, fats: 8.3, ig: 0},
  {name: 'Chataigne fraîche', calories: 200, proteins: 4, carbohydrates: 42, fats: 3, ig: 0},
  {name: 'Cheval rôti', calories: 142, proteins: 23.9, carbohydrates: 0, fats: 5, ig: 0},
  {name: 'Chocapic', calories: 375, proteins: 7.3, carbohydrates: 75.8, fats: 4.8, ig: 0},
  {name: 'Chocolat à croquer', calories: 500, proteins: 7, carbohydrates: 64, fats: 24, ig: 0},
  {name: 'Chocolat au lait', calories: 550, proteins: 6, carbohydrates: 55, fats: 34, ig: 0},
  {name: 'Chocolat en poudre', calories: 400, proteins: 5, carbohydrates: 86, fats: 4, ig: 0},
  {name: 'Chou cru', calories: 27, proteins: 1.4, carbohydrates: 5, fats: 0, ig: 0},
  {name: 'Chou cuit', calories: 41, proteins: 1.5, carbohydrates: 8, fats: 0.4, ig: 0},
  {name: 'Choucroute', calories: 27, proteins: 1.3, carbohydrates: 4.8, fats: 0.3, ig: 0},
  {name: 'Chou-fleur', calories: 30, proteins: 2.4, carbohydrates: 4.5, fats: 0, ig: 0},
  {name: 'Choux de bruxelles', calories: 55, proteins: 4.3, carbohydrates: 8, fats: 0.6, ig: 0},
  {name: 'Ciboulette crue', calories: 30, proteins: 3.3, carbohydrates: 4.4, fats: 0.7, ig: 0},
  {name: 'Ciboulette lyophilisée', calories: 311, proteins: 21, carbohydrates: 64.3, fats: 3.5, ig: 0},
  {name: 'Citron jaune', calories: 34, proteins: 0.7, carbohydrates: 6.5, fats: 0.5, ig: 0},
  {name: 'Citron vert', calories: 31, proteins: 0.5, carbohydrates: 7, fats: 0, ig: 0},
  {name: 'Citrouille', calories: 31, proteins: 1.3, carbohydrates: 6, fats: 0, ig: 0},
  {name: 'Clous de girofle', calories: 322.7, proteins: 6, carbohydrates: 61, fats: 20, ig: 0},
  {name: 'Coca-cola (1 canette 33 cl)', calories: 147.87, proteins: 0, carbohydrates: 35.16, fats: 0, ig: 0},
  {name: 'Coeur de boeuf', calories: 140, proteins: 22, carbohydrates: 0.3, fats: 5.8, ig: 0},
  {name: 'Coing', calories: 58, proteins: 0.4, carbohydrates: 14, fats: 0, ig: 0},
  {name: 'Colin (merlu)', calories: 91, proteins: 17, carbohydrates: 0, fats: 2.5, ig: 0},
  {name: 'Concombre', calories: 12, proteins: 0.7, carbohydrates: 2, fats: 0, ig: 0},
  {name: 'Cône glacé écrémé', calories: 377, proteins: 10, carbohydrates: 77.9, fats: 2.4, ig: 0},
  {name: 'Confiture', calories: 270, proteins: 1, carbohydrates: 66, fats: 0, ig: 0},
  {name: 'Congre (poisson)', calories: 110, proteins: 20, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Coquille st-jacques', calories: 92, proteins: 15, carbohydrates: 3.4, fats: 0.4, ig: 0},
  {name: 'Corn flakes', calories: 368, proteins: 11, carbohydrates: 76, fats: 2.3, ig: 0},
  {name: 'Cornichon', calories: 13, proteins: 0.7, carbohydrates: 2.3, fats: 0, ig: 0},
  {name: 'Cote d\'agneau', calories: 242, proteins: 20, carbohydrates: 0, fats: 18, ig: 0},
  {name: 'Cote de boeuf rôtie', calories: 199, proteins: 23, carbohydrates: 0, fats: 11.9, ig: 0},
  {name: 'Côtelette de porc', calories: 319, proteins: 21.7, carbohydrates: 0, fats: 25.8, ig: 0},
  {name: 'Courgettes', calories: 33, proteins: 1.3, carbohydrates: 6.5, fats: 0, ig: 0},
  {name: 'Couscous', calories: 120, proteins: 3.5, carbohydrates: 22, fats: 2, ig: 0},
  {name: 'Crabe (chair)', calories: 108, proteins: 18.5, carbohydrates: 0.5, fats: 3.5, ig: 0},
  {name: 'Crème chantilly', calories: 316, proteins: 2.3, carbohydrates: 3, fats: 32.7, ig: 0},
  {name: 'Crème d\'asperges (soupe)', calories: 178, proteins: 4.5, carbohydrates: 21.5, fats: 8, ig: 0},
  {name: 'Crème fraîche', calories: 282, proteins: 3.5, carbohydrates: 4, fats: 28, ig: 0},
  {name: 'Cresson', calories: 21, proteins: 1.7, carbohydrates: 2.9, fats: 0.3, ig: 0},
  {name: 'Crevettes', calories: 105, proteins: 19, carbohydrates: 0.5, fats: 3, ig: 0},
  {name: 'Croissant', calories: 348, proteins: 7, carbohydrates: 48, fats: 15, ig: 0},
  {name: 'Cuisse poulet rôti', calories: 169, proteins: 22, carbohydrates: 0, fats: 9, ig: 0},
  {name: 'Cuisses de grenouille', calories: 69, proteins: 16.4, carbohydrates: 0, fats: 0.3, ig: 0},
  {name: 'Cumin', calories: 333, proteins: 19.8, carbohydrates: 49.9, fats: 14.6, ig: 0},
  {name: 'Curry', calories: 325, proteins: 12.7, carbohydrates: 58, fats: 13.8, ig: 0},
  {name: 'Daiquiri', calories: 185, proteins: 0, carbohydrates: 7, fats: 0.06, ig: 0},
  {name: 'Dattes', calories: 315, proteins: 2, carbohydrates: 75, fats: 0.6, ig: 0},
  {name: 'Dorade', calories: 91, proteins: 16, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Eau minérale', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Echalote', calories: 75, proteins: 1.3, carbohydrates: 17, fats: 0, ig: 0},
  {name: 'Echalotes', calories: 72, proteins: 2.5, carbohydrates: 16.8, fats: 0, ig: 0},
  {name: 'Echalotes lyophilisées', calories: 348, proteins: 12.3, carbohydrates: 80.7, fats: 0.5, ig: 0},
  {name: 'Eclair (gâteau)', calories: 239, proteins: 6, carbohydrates: 23, fats: 13.6, ig: 0},
  {name: 'Ecrevisse', calories: 64, proteins: 14, carbohydrates: 1, fats: 0.4, ig: 0},
  {name: 'Endives', calories: 24, proteins: 1.5, carbohydrates: 4, fats: 0, ig: 0},
  {name: 'Epaule d\'agneau rôtie', calories: 168, proteins: 21, carbohydrates: 0, fats: 9, ig: 0},
  {name: 'Ephynal roche', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Epinard', calories: 27, proteins: 2.3, carbohydrates: 4, fats: 0, ig: 0},
  {name: 'Escalope de dinde', calories: 116, proteins: 20, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Escalope de veau', calories: 139, proteins: 22, carbohydrates: 0, fats: 5.6, ig: 0},
  {name: 'Escargot', calories: 75, proteins: 15, carbohydrates: 2, fats: 0.8, ig: 0},
  {name: 'Espadon', calories: 132, proteins: 21.6, carbohydrates: 0, fats: 4.5, ig: 0},
  {name: 'Estragon', calories: 295.5, proteins: 22.8, carbohydrates: 50, fats: 7, ig: 0},
  {name: 'Esturgeon', calories: 115, proteins: 17.6, carbohydrates: 0, fats: 4.5, ig: 0},
  {name: 'Evian', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Extrait de vanille', calories: 288, proteins: 0, carbohydrates: 12.7, fats: 0, ig: 0},
  {name: 'Faisan', calories: 108, proteins: 22, carbohydrates: 0.5, fats: 2, ig: 0},
  {name: 'Farine de blé', calories: 384, proteins: 8.9, carbohydrates: 85, fats: 0.9, ig: 0},
  {name: 'Faux-filet', calories: 148, proteins: 22, carbohydrates: 0.5, fats: 6.5, ig: 0},
  {name: 'Fenouil', calories: 21, proteins: 1.9, carbohydrates: 2.8, fats: 0, ig: 0},
  {name: 'Feuille de coriandre séchée', calories: 278.9, proteins: 21.9, carbohydrates: 52, fats: 4.8, ig: 0},
  {name: 'Feuilles de laurier (émietées)', calories: 313.5, proteins: 7.6, carbohydrates: 75, fats: 8.4, ig: 0},
  {name: 'Feve seche', calories: 345, proteins: 23, carbohydrates: 60, fats: 1.5, ig: 0},
  {name: 'Figues', calories: 84, proteins: 0.8, carbohydrates: 19, fats: 0.4, ig: 0},
  {name: 'Figues seches', calories: 257, proteins: 4.3, carbohydrates: 62, fats: 1, ig: 0},
  {name: 'Filet de boeuf', calories: 143, proteins: 24, carbohydrates: 0.5, fats: 5, ig: 0},
  {name: 'Fletan', calories: 125, proteins: 22.5, carbohydrates: 0, fats: 5, ig: 0},
  {name: 'Flocons d\'avoine', calories: 371, proteins: 13.5, carbohydrates: 67, fats: 5.5, ig: 0},
  {name: 'Foie de veau', calories: 138, proteins: 18.5, carbohydrates: 2.4, fats: 6, ig: 0},
  {name: 'Foie gras', calories: 477, proteins: 13, carbohydrates: 5, fats: 45, ig: 0},
  {name: 'Fraises', calories: 37, proteins: 0.7, carbohydrates: 7.5, fats: 0.5, ig: 0},
  {name: 'Framboise', calories: 43, proteins: 1, carbohydrates: 8.5, fats: 0.5, ig: 0},
  {name: 'Frites', calories: 318, proteins: 4.4, carbohydrates: 36.3, fats: 17, ig: 0},
  {name: 'Fromage blanc 0mg', calories: 56, proteins: 9, carbohydrates: 4.5, fats: 0, ig: 0},
  {name: 'Fromage blanc 20mg', calories: 113, proteins: 9, carbohydrates: 8, fats: 5, ig: 0},
  {name: 'Fromage brie', calories: 271, proteins: 17, carbohydrates: 3.5, fats: 21, ig: 0},
  {name: 'Fromage cantal', calories: 385, proteins: 23, carbohydrates: 5.8, fats: 30, ig: 0},
  {name: 'Fromage cheddar', calories: 395, proteins: 24, carbohydrates: 1.5, fats: 31.9, ig: 0},
  {name: 'Fromage de chevre', calories: 320, proteins: 20, carbohydrates: 15, fats: 20, ig: 0},
  {name: 'Fromage de chevre (de 50 grammes)', calories: 160, proteins: 10, carbohydrates: 7.5, fats: 10, ig: 0},
  {name: 'Fromage de mozzarella', calories: 271, proteins: 18.5, carbohydrates: 2, fats: 20.9, ig: 0},
  {name: 'Fromage gouda', calories: 347, proteins: 24, carbohydrates: 2, fats: 26.4, ig: 0},
  {name: 'Fromage munster', calories: 320, proteins: 21, carbohydrates: 5, fats: 24, ig: 0},
  {name: 'Fruits au sirop', calories: 103, proteins: 0.5, carbohydrates: 25, fats: 0, ig: 0},
  {name: 'Fruits secs melangés', calories: 335, proteins: 2.4, carbohydrates: 78, fats: 1.5, ig: 0},
  {name: 'Germe de blé', calories: 387, proteins: 29, carbohydrates: 48.5, fats: 8.5, ig: 0},
  {name: 'Gigot de mouton rôti', calories: 214, proteins: 22, carbohydrates: 0, fats: 14, ig: 0},
  {name: 'Gin', calories: 255, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Gin and tonic', calories: 171, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Gingembre', calories: 347, proteins: 9, carbohydrates: 70.8, fats: 5.9, ig: 0},
  {name: 'Glace à la vanille (1 boule = 30 g)', calories: 186, proteins: 4, carbohydrates: 20, fats: 10, ig: 0},
  {name: 'Glace au chocolat', calories: 200, proteins: 4, carbohydrates: 21, fats: 11, ig: 0},
  {name: 'Glace au citron', calories: 125, proteins: 0.4, carbohydrates: 31, fats: 0, ig: 0},
  {name: 'Goujon', calories: 68, proteins: 12, carbohydrates: 0, fats: 1.5, ig: 0},
  {name: 'Goyave', calories: 53, proteins: 0.7, carbohydrates: 11, fats: 0.6, ig: 0},
  {name: 'Graines d\'anis', calories: 337.3, proteins: 17.6, carbohydrates: 50, fats: 15.9, ig: 0},
  {name: 'Graines de coriandre', calories: 297.5, proteins: 12.4, carbohydrates: 55, fats: 17.8, ig: 0},
  {name: 'Graines de cumin', calories: 374.5, proteins: 17.8, carbohydrates: 44, fats: 22.3, ig: 0},
  {name: 'Graines de fenouil', calories: 344.9, proteins: 15.8, carbohydrates: 52.3, fats: 14.9, ig: 0},
  {name: 'Graines de pavots', calories: 533, proteins: 18, carbohydrates: 23.7, fats: 44.7, ig: 0},
  {name: 'Groseilles', calories: 46, proteins: 1, carbohydrates: 9.5, fats: 0.4, ig: 0},
  {name: 'Gruyère', calories: 430, proteins: 30.6, carbohydrates: 0.3, fats: 33.6, ig: 0},
  {name: 'Haddock', calories: 101, proteins: 23, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Haddock fumé', calories: 95, proteins: 21.5, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Hareng', calories: 212, proteins: 19, carbohydrates: 0, fats: 15, ig: 0},
  {name: 'Hareng fumé', calories: 215, proteins: 22, carbohydrates: 0, fats: 14, ig: 0},
  {name: 'Haricots blancs', calories: 128, proteins: 8, carbohydrates: 23, fats: 0.5, ig: 0},
  {name: 'Haricots rouges', calories: 328, proteins: 22.8, carbohydrates: 58, fats: 1.5, ig: 0},
  {name: 'Haricots secs', calories: 337, proteins: 21, carbohydrates: 60, fats: 1.5, ig: 0},
  {name: 'Haricots verts', calories: 35, proteins: 2.3, carbohydrates: 6, fats: 0, ig: 0},
  {name: 'Homard', calories: 94, proteins: 18, carbohydrates: 1, fats: 2, ig: 0},
  {name: 'Huile de colza', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huile de germe de blé', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huile de noix', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huile de soja', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huile de tournesol', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huile d\'olive', calories: 900, proteins: 0, carbohydrates: 0, fats: 100, ig: 0},
  {name: 'Huîtres', calories: 73, proteins: 9, carbohydrates: 4.5, fats: 2, ig: 0},
  {name: 'Jambon de dinde', calories: 123, proteins: 20, carbohydrates: 0.3, fats: 4.8, ig: 0},
  {name: 'Jambon maigre', calories: 112, proteins: 21, carbohydrates: 0.5, fats: 2.9, ig: 0},
  {name: 'Jambon ordinaire', calories: 170, proteins: 18.5, carbohydrates: 1.5, fats: 10, ig: 0},
  {name: 'Jaune d\'oeuf', calories: 358, proteins: 16.8, carbohydrates: 1.8, fats: 30.9, ig: 0},
  {name: 'Jus d\'ananas', calories: 57, proteins: 0.3, carbohydrates: 13.8, fats: 0, ig: 0},
  {name: 'Jus de carotte', calories: 41, proteins: 0.9, carbohydrates: 9.6, fats: 0, ig: 0},
  {name: 'Jus de citron', calories: 5, proteins: 0.06, carbohydrates: 1.3, fats: 0, ig: 0},
  {name: 'Jus de legume cocktail', calories: 19.5, proteins: 0.6, carbohydrates: 4.6, fats: 0, ig: 0},
  {name: 'Jus de pamplemousse', calories: 39, proteins: 0.5, carbohydrates: 9.3, fats: 0, ig: 0},
  {name: 'Jus de pomme', calories: 49, proteins: 0, carbohydrates: 12, fats: 0, ig: 0},
  {name: 'Jus de raisin', calories: 66, proteins: 0.6, carbohydrates: 16, fats: 0, ig: 0},
  {name: 'Jus de tomate', calories: 20, proteins: 1, carbohydrates: 4.4, fats: 0.04, ig: 35},
  {name: 'Jus d\'orange', calories: 51, proteins: 0, carbohydrates: 12.8, fats: 0, ig: 0},
  {name: 'Kaki', calories: 81, proteins: 0.8, carbohydrates: 19, fats: 0, ig: 0},
  {name: 'Ketchup', calories: 102, proteins: 0.4, carbohydrates: 25, fats: 0, ig: 0},
  {name: 'Kiwi', calories: 46, proteins: 0.7, carbohydrates: 11, fats: 0.3, ig: 0},
  {name: 'Lait de soja', calories: 49, proteins: 4, carbohydrates: 3, fats: 2.3, ig: 0},
  {name: 'Lait demi-écrémé', calories: 43, proteins: 2.8, carbohydrates: 4.5, fats: 1.5, ig: 0},
  {name: 'Lait écrémé liquide', calories: 35, proteins: 3.4, carbohydrates: 4.9, fats: 0, ig: 0},
  {name: 'Lait écrémé poudre', calories: 358, proteins: 35, carbohydrates: 52, fats: 0.7, ig: 0},
  {name: 'Lait entier liquide', calories: 63, proteins: 3.4, carbohydrates: 4.9, fats: 3.4, ig: 0},
  {name: 'Laitue', calories: 17, proteins: 1.3, carbohydrates: 2.6, fats: 0, ig: 0},
  {name: 'Langouste', calories: 98, proteins: 17, carbohydrates: 0.5, fats: 2, ig: 0},
  {name: 'Langue de boeuf', calories: 229, proteins: 18.8, carbohydrates: 0.4, fats: 17, ig: 0},
  {name: 'Lapin chasseur', calories: 139, proteins: 28, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Lapin cuit en civet', calories: 139, proteins: 28, carbohydrates: 0, fats: 7, ig: 0},
  {name: 'Laroscorbine effervescente', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Lentilles cuites', calories: 115, proteins: 8.9, carbohydrates: 20, fats: 0.4, ig: 0},
  {name: 'Levure de bière', calories: 381, proteins: 49, carbohydrates: 32, fats: 6.3, ig: 0},
  {name: 'Lièvre', calories: 98, proteins: 22, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Limande', calories: 76, proteins: 16.5, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Liqueur', calories: 574, proteins: 0, carbohydrates: 78, fats: 0, ig: 0},
  {name: 'Lotte', calories: 86, proteins: 18, carbohydrates: 0, fats: 1.5, ig: 0},
  {name: 'Macaronis cuits', calories: 140, proteins: 5, carbohydrates: 29, fats: 0.4, ig: 0},
  {name: 'Mais (grains)', calories: 360, proteins: 9.4, carbohydrates: 74, fats: 4.3, ig: 0},
  {name: 'Mandarine', calories: 41, proteins: 0.5, carbohydrates: 9.4, fats: 0, ig: 0},
  {name: 'Mangue', calories: 64, proteins: 0.4, carbohydrates: 15, fats: 0, ig: 0},
  {name: 'Maquereau (filets)', calories: 184, proteins: 19, carbohydrates: 0, fats: 12, ig: 0},
  {name: 'Maquereau à la poele', calories: 224, proteins: 20, carbohydrates: 0, fats: 16, ig: 0},
  {name: 'Maquereau en boîte', calories: 151, proteins: 22, carbohydrates: 0, fats: 7, ig: 0},
  {name: 'Margarine dure', calories: 34, proteins: 0.04, carbohydrates: 0.04, fats: 3.8, ig: 0},
  {name: 'Margarine en boîte', calories: 34, proteins: 0, carbohydrates: 0, fats: 3.8, ig: 0},
  {name: 'Marjolaine séchée', calories: 271.5, proteins: 12.7, carbohydrates: 60.6, fats: 7, ig: 0},
  {name: 'Marrons grillés', calories: 362, proteins: 7.4, carbohydrates: 72, fats: 5, ig: 0},
  {name: 'Martini', calories: 156, proteins: 0, carbohydrates: 0.8, fats: 0, ig: 0},
  {name: 'Mayonnaise', calories: 99, proteins: 0.15, carbohydrates: 0.37, fats: 11, ig: 0},
  {name: 'Melon', calories: 37, proteins: 0.8, carbohydrates: 8.4, fats: 0, ig: 0},
  {name: 'Merlan filet nature', calories: 90, proteins: 18, carbohydrates: 0, fats: 2, ig: 0},
  {name: 'Merlan frit', calories: 134, proteins: 20, carbohydrates: 0, fats: 6, ig: 0},
  {name: 'Miel', calories: 312, proteins: 0.4, carbohydrates: 77, fats: 0, ig: 0},
  {name: 'Milo', calories: 399, proteins: 6.6, carbohydrates: 86.3, fats: 3, ig: 0},
  {name: 'Mortadelle', calories: 263, proteins: 18, carbohydrates: 0.5, fats: 21, ig: 0},
  {name: 'Moules nature', calories: 76, proteins: 12, carbohydrates: 2.5, fats: 2, ig: 0},
  {name: 'Moules preparées', calories: 146, proteins: 20, carbohydrates: 6, fats: 4, ig: 0},
  {name: 'Moutarde', calories: 105, proteins: 5.9, carbohydrates: 5.3, fats: 6.7, ig: 0},
  {name: 'Muesli fruits', calories: 371, proteins: 8, carbohydrates: 60, fats: 11, ig: 0},
  {name: 'Mures', calories: 57, proteins: 0.6, carbohydrates: 12.8, fats: 0.4, ig: 0},
  {name: 'Myrtilles', calories: 80, proteins: 1, carbohydrates: 15.5, fats: 0.5, ig: 0},
  {name: 'Navet', calories: 31, proteins: 1, carbohydrates: 7, fats: 0, ig: 0},
  {name: 'Nectarine', calories: 59, proteins: 1, carbohydrates: 13, fats: 0.4, ig: 0},
  {name: 'Noisette', calories: 566, proteins: 14, carbohydrates: 15, fats: 50, ig: 0},
  {name: 'Noix de coco', calories: 362, proteins: 4, carbohydrates: 10, fats: 34, ig: 0},
  {name: 'Noix de muscade', calories: 524.7, proteins: 5.8, carbohydrates: 49.3, fats: 36.3, ig: 0},
  {name: 'Oeuf', calories: 149, proteins: 12.5, carbohydrates: 1, fats: 10, ig: 0},
  {name: 'Oeuf au plat', calories: 199, proteins: 13.5, carbohydrates: 1.4, fats: 15, ig: 0},
  {name: 'Oeuf brouillé', calories: 166, proteins: 11, carbohydrates: 2, fats: 12, ig: 0},
  {name: 'Oeuf dur', calories: 155, proteins: 12.6, carbohydrates: 1, fats: 10.6, ig: 0},
  {name: 'Oeuf poché', calories: 149, proteins: 12.4, carbohydrates: 1, fats: 10, ig: 0},
  {name: 'Oignon', calories: 43, proteins: 1.4, carbohydrates: 9, fats: 0, ig: 0},
  {name: 'Oignon en poudre', calories: 346.7, proteins: 10, carbohydrates: 80.7, fats: 1, ig: 0},
  {name: 'Olive verte', calories: 193, proteins: 0.7, carbohydrates: 18, fats: 7, ig: 0},
  {name: 'Omelette', calories: 152, proteins: 10.3, carbohydrates: 1, fats: 11.4, ig: 0},
  {name: 'Onglet', calories: 182, proteins: 24, carbohydrates: 0.5, fats: 9, ig: 0},
  {name: 'Orange', calories: 50, proteins: 1, carbohydrates: 11, fats: 0, ig: 0},
  {name: 'Origan', calories: 305.9, proteins: 11, carbohydrates: 64.4, fats: 10.3, ig: 0},
  {name: 'Oseille', calories: 25, proteins: 2.7, carbohydrates: 2.5, fats: 0.5, ig: 0},
  {name: 'Pain au raisin', calories: 262, proteins: 6.5, carbohydrates: 52, fats: 3, ig: 0},
  {name: 'Pain blanc', calories: 255, proteins: 7, carbohydrates: 55, fats: 0.8, ig: 0},
  {name: 'Pain complet', calories: 240, proteins: 8, carbohydrates: 50, fats: 0.8, ig: 0},
  {name: 'Pain de seigle', calories: 241, proteins: 7, carbohydrates: 51, fats: 1},
  {name: 'Pain d\'épice', calories: 385, proteins: 5, carbohydrates: 72, fats: 5, ig: 0},
  {name: 'Pain grille', calories: 355, proteins: 13, carbohydrates: 72.9, fats: 6.5, ig: 0},
  {name: 'Pamplemousse', calories: 40, proteins: 0.6, carbohydrates: 9, fats: 0, ig: 0},
  {name: 'Papaye', calories: 44, proteins: 0.6, carbohydrates: 10, fats: 0, ig: 0},
  {name: 'Paprika', calories: 289, proteins: 14.8, carbohydrates: 55.7, fats: 13, ig: 0},
  {name: 'Parmesan', calories: 390, proteins: 36, carbohydrates: 3, fats: 26, ig: 0},
  {name: 'Pâté d\'amandes', calories: 462, proteins: 11.9, carbohydrates: 44, fats: 26, ig: 0},
  {name: 'Pâté de foie', calories: 454, proteins: 14, carbohydrates: 5, fats: 42, ig: 0},
  {name: 'Pâtes (pesees crues)', calories: 361, proteins: 13, carbohydrates: 75, fats: 1, ig: 0},
  {name: 'Pâtes (pesees cuites)', calories: 140, proteins: 5, carbohydrates: 29, fats: 0.4, ig: 0},
  {name: 'Pâtes au gluten', calories: 348, proteins: 20, carbohydrates: 62, fats: 2, ig: 0},
  {name: 'Pavé de boeuf', calories: 173, proteins: 28, carbohydrates: 0.5, fats: 6.5, ig: 0},
  {name: 'Pêche', calories: 49, proteins: 0.6, carbohydrates: 11.5, fats: 0, ig: 0},
  {name: 'Pêche au sirop', calories: 88, proteins: 0.5, carbohydrates: 21, fats: 0, ig: 0},
  {name: 'Perche', calories: 105, proteins: 19, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Perrier', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Persil', calories: 54, proteins: 3.7, carbohydrates: 7.5, fats: 1, ig: 0},
  {name: 'Persil séché', calories: 276, proteins: 22.4, carbohydrates: 51.7, fats: 4.4, ig: 0},
  {name: 'Petit suisse', calories: 191, proteins: 10, carbohydrates: 4, fats: 15, ig: 0},
  {name: 'Petits pois', calories: 90, proteins: 6.5, carbohydrates: 15, fats: 0.5, ig: 0},
  {name: 'Pieuvre, poulpe', calories: 84, proteins: 14.7, carbohydrates: 1.8, fats: 2, ig: 0},
  {name: 'Piment en poudre', calories: 314, proteins: 12.3, carbohydrates: 54.7, fats: 16.8, ig: 0},
  {name: 'Pissenlit', calories: 48, proteins: 2.7, carbohydrates: 8, fats: 0.6, ig: 0},
  {name: 'Pizza calzone', calories: 269, proteins: 13, carbohydrates: 38, fats: 9, ig: 0},
  {name: 'Pizza jambon-fromage', calories: 254, proteins: 9.5, carbohydrates: 36, fats: 8, ig: 0},
  {name: 'Poire', calories: 53, proteins: 0.5, carbohydrates: 12, fats: 0.3, ig: 0},
  {name: 'Poireau', calories: 41, proteins: 2, carbohydrates: 7.5, fats: 0.3, ig: 0},
  {name: 'Poires au sirop léger', calories: 72, proteins: 0.3, carbohydrates: 16, fats: 0.3, ig: 0},
  {name: 'Poires au sirop sucrée', calories: 108, proteins: 0.3, carbohydrates: 26, fats: 0.3, ig: 0},
  {name: 'Pois chiche', calories: 364, proteins: 18, carbohydrates: 61, fats: 6, ig: 0},
  {name: 'Poivre', calories: 6, proteins: 0, carbohydrates: 1.3, fats: 0.07, ig: 0},
  {name: 'Poivre blanc', calories: 296, proteins: 10.4, carbohydrates: 68.6, fats: 2, ig: 0},
  {name: 'Poivre de Jamaïque', calories: 262.6, proteins: 6, carbohydrates: 72, fats: 8.7, ig: 0},
  {name: 'Poivre noir', calories: 255, proteins: 10.9, carbohydrates: 64.8, fats: 3.3, ig: 0},
  {name: 'Poivre rouge (ou de Cayenne)', calories: 318, proteins: 12, carbohydrates: 56.6, fats: 17.3, ig: 0},
  {name: 'Poivron', calories: 22, proteins: 1, carbohydrates: 4, fats: 0, ig: 0},
  {name: 'Pomme', calories: 58, proteins: 0, carbohydrates: 13.5, fats: 0.4, ig: 0},
  {name: 'Pomme de terre', calories: 65, proteins: 2, carbohydrates: 14, fats: 0, ig: 0},
  {name: 'Pop corn (maïs)', calories: 360, proteins: 4.5, carbohydrates: 80, fats: 1, ig: 0},
  {name: 'Praire (crustacé)', calories: 120, proteins: 21.7, carbohydrates: 4.4, fats: 1.7, ig: 0},
  {name: 'Prune', calories: 53, proteins: 0.8, carbohydrates: 11, fats: 0, ig: 0},
  {name: 'Pruneau', calories: 295, proteins: 2.3, carbohydrates: 70, fats: 0.6, ig: 0},
  {name: 'Punch', calories: 230, proteins: 0.5, carbohydrates: 18.5, fats: 0, ig: 0},
  {name: 'Radis', calories: 21, proteins: 1, carbohydrates: 3.9, fats: 0, ig: 0},
  {name: 'Ragoût de boeuf', calories: 171, proteins: 28, carbohydrates: 0, fats: 5.5, ig: 0},
  {name: 'Raie', calories: 93, proteins: 21, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Raisin', calories: 74, proteins: 0.9, carbohydrates: 16, fats: 0.7, ig: 0},
  {name: 'Raisins secs', calories: 296, proteins: 2.5, carbohydrates: 78.5, fats: 0.5, ig: 0},
  {name: 'Rhum', calories: 231, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Rillettes', calories: 601, proteins: 22, carbohydrates: 0, fats: 57, ig: 0},
  {name: 'Riz blanc (cuit)', calories: 132, proteins: 2.7, carbohydrates: 29, fats: 0, ig: 0},
  {name: 'Riz complet (cuit)', calories: 109, proteins: 2.5, carbohydrates: 22.5, fats: 1, ig: 0},
  {name: 'Rognon de boeuf', calories: 117, proteins: 21.7, carbohydrates: 0.8, fats: 3, ig: 0},
  {name: 'Rognons de veau', calories: 133, proteins: 22.4, carbohydrates: 0, fats: 4.82, ig: 0},
  {name: 'Romarin séché', calories: 331.5, proteins: 4.9, carbohydrates: 64, fats: 15, ig: 0},
  {name: 'Roquefort', calories: 368, proteins: 21.5, carbohydrates: 2, fats: 30.5, ig: 0},
  {name: 'Rôti de dinde', calories: 124, proteins: 21.5, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Rôti de porc', calories: 202, proteins: 21.6, carbohydrates: 0, fats: 12.8, ig: 0},
  {name: 'Rôti de veau', calories: 121, proteins: 23.9, carbohydrates: 0, fats: 2.8, ig: 0},
  {name: 'Roussette', calories: 151, proteins: 17.5, carbohydrates: 0, fats: 9, ig: 0},
  {name: 'Rumsteak', calories: 166, proteins: 23, carbohydrates: 0.5, fats: 8, ig: 0},
  {name: 'Safran', calories: 310, proteins: 11.4, carbohydrates: 65.4, fats: 5.9, ig: 0},
  {name: 'Safran des indes', calories: 354, proteins: 7.8, carbohydrates: 64.9, fats: 9.9, ig: 0},
  {name: 'Salade de maïs', calories: 7.5, proteins: 0.6, carbohydrates: 1, fats: 0, ig: 0},
  {name: 'Salade de thon', calories: 159, proteins: 13.6, carbohydrates: 8, fats: 8, ig: 0},
  {name: 'Salsifis', calories: 73, proteins: 3.6, carbohydrates: 13.6, fats: 0.9, ig: 0},
  {name: 'Sandwich jambon-beurre', calories: 356, proteins: 10.3, carbohydrates: 36, fats: 18.8, ig: 0},
  {name: 'Sandwich jambon-fromage', calories: 352, proteins: 20.7, carbohydrates: 33.3, fats: 15.5, ig: 0},
  {name: 'Sardine entiere', calories: 142, proteins: 22, carbohydrates: 0, fats: 6, ig: 0},
  {name: 'Sardines à l\'huile', calories: 191, proteins: 22.6, carbohydrates: 0, fats: 10.5, ig: 0},
  {name: 'Sauce aioli', calories: 747, proteins: 2, carbohydrates: 1.5, fats: 80, ig: 0},
  {name: 'Sauce salade', calories: 522, proteins: 2, carbohydrates: 3, fats: 55, ig: 0},
  {name: 'Sauce spaghettis', calories: 33, proteins: 1, carbohydrates: 5, fats: 1, ig: 0},
  {name: 'Sauce tomate', calories: 50, proteins: 1.15, carbohydrates: 10.7, fats: 1, ig: 35},
  {name: 'Saucisse de francfort', calories: 236, proteins: 10.5, carbohydrates: 2.5, fats: 20.5, ig: 0},
  {name: 'Saucisson sec', calories: 546, proteins: 24, carbohydrates: 0, fats: 50, ig: 0},
  {name: 'Sauge', calories: 314.8, proteins: 10.6, carbohydrates: 60.7, fats: 12.7, ig: 0},
  {name: 'Saumon', calories: 179, proteins: 20, carbohydrates: 0, fats: 11, ig: 0},
  {name: 'Seiche', calories: 67, proteins: 14.8, carbohydrates: 0.7, fats: 0.6, ig: 0},
  {name: 'Sel', calories: 0, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Semoule de blé', calories: 345, proteins: 10, carbohydrates: 74, fats: 1, ig: 0},
  {name: 'Semoule de maïs', calories: 365, proteins: 8.8, carbohydrates: 78, fats: 1, ig: 0},
  {name: 'Soja (grain sec)', calories: 422, proteins: 35, carbohydrates: 30, fats: 18, ig: 0},
  {name: 'Sole', calories: 75, proteins: 16.5, carbohydrates: 0, fats: 1, ig: 0},
  {name: 'Soupe à l\'oignon', calories: 64, proteins: 3.7, carbohydrates: 8, fats: 1.8},
  {name: 'Soupe au poulet', calories: 180, proteins: 12.7, carbohydrates: 17.3, fats: 6.6, ig: 0},
  {name: 'Soupe aux champignons', calories: 127, proteins: 2.3, carbohydrates: 9.4, fats: 8.9, ig: 0},
  {name: 'Soupe legumes', calories: 123, proteins: 3.5, carbohydrates: 19, fats: 3.7, ig: 0},
  {name: 'Soupe minestrone', calories: 84, proteins: 4, carbohydrates: 11, fats: 2.5, ig: 0},
  {name: 'Spaghettis (non cuits)', calories: 385, proteins: 13, carbohydrates: 75, fats: 1.5, ig: 0},
  {name: 'Spaghettis cuits', calories: 140, proteins: 5, carbohydrates: 29, fats: 0.5, ig: 0},
  {name: 'Steak aloyau', calories: 163, proteins: 25, carbohydrates: 0, fats: 7, ig: 0},
  {name: 'Steak hache 5 mg', calories: 124, proteins: 21, carbohydrates: 0, fats: 4.4, ig: 0},
  {name: 'Sucre blanc', calories: 400, proteins: 0, carbohydrates: 100, fats: 0, ig: 0},
  {name: 'Sucre brun', calories: 376, proteins: 0, carbohydrates: 97.3, fats: 0, ig: 0},
  {name: 'Sucre en poudre', calories: 389, proteins: 0, carbohydrates: 99.5, fats: 0, ig: 0},
  {name: 'Tapioca (manioc)', calories: 348, proteins: 0.6, carbohydrates: 86, fats: 0, ig: 0},
  {name: 'Tarte aux cerises', calories: 313, proteins: 3, carbohydrates: 45.3, fats: 13.3, ig: 0},
  {name: 'Tarte aux fraises', calories: 191, proteins: 2, carbohydrates: 29, fats: 7.5, ig: 0},
  {name: 'Tarte aux pommes', calories: 308, proteins: 2.6, carbohydrates: 45, fats: 13, ig: 0},
  {name: 'Thé', calories: 1, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Thon cru', calories: 122, proteins: 19.8, carbohydrates: 0, fats: 4, ig: 0},
  {name: 'Thon en boîte', calories: 111, proteins: 25, carbohydrates: 0, fats: 0.42, ig: 0},
  {name: 'Thym frais', calories: 101, proteins: 5.6, carbohydrates: 24.5, fats: 1.7, ig: 0},
  {name: 'Thym moulu', calories: 276, proteins: 9, carbohydrates: 63.9, fats: 7.4, ig: 0},
  {name: 'Tomate', calories: 21, proteins: 1, carbohydrates: 3.7, fats: 0.3, ig: 30},
  {name: 'Tripes', calories: 94, proteins: 18, carbohydrates: 1, fats: 2, ig: 0},
  {name: 'Truite', calories: 128, proteins: 22.4, carbohydrates: 0, fats: 3.6, ig: 0},
  {name: 'Truite de mer', calories: 104, proteins: 18, carbohydrates: 0, fats: 3, ig: 0},
  {name: 'Turbot', calories: 118, proteins: 16, carbohydrates: 0, fats: 6, ig: 0},
  {name: 'Vin blanc', calories: 70, proteins: 0, carbohydrates: 0.8, fats: 0, ig: 0},
  {name: 'Vin rose', calories: 73, proteins: 0, carbohydrates: 1.5, fats: 0, ig: 0},
  {name: 'Vin rouge', calories: 74, proteins: 0, carbohydrates: 1.8, fats: 0, ig: 0},
  {name: 'Vinaigre', calories: 9, proteins: 0, carbohydrates: 1, fats: 0, ig: 5},
  {name: 'Vinaigrette type (olive)', calories: 260.54, proteins: 0.44, carbohydrates: 2.19, fats: 27.39, ig: 0},
  {name: 'Vodka', calories: 238, proteins: 0, carbohydrates: 0, fats: 0, ig: 0},
  {name: 'Whisky', calories: 238, proteins: 0, carbohydrates: 0.03, fats: 0, ig: 0},
  {name: 'Yaourt aux fruits', calories: 115, proteins: 3, carbohydrates: 19.6, fats: 2.7, ig: 0},
  {name: 'Yaourt nature', calories: 65, proteins: 4, carbohydrates: 4.6, fats: 3.5, ig: 35}
];

@Injectable()
export class FoodService {
  getFoods():Food[] {
    return FOODS;
  }
}
